### ISSUE TITLE
Could not load type "App\Form\DependentFilteredEntityType": class does not exist.

### ISSUE THREAD

**Issue by methodeprog** [EvercodeLab/DependentSelectBundle#12]
Hi ,
Please im trying the bundle i get an issue
I use Symfony 4

This is my logs

request.CRITICAL: Uncaught PHP Exception Symfony\Component\Form\Exception\InvalidArgumentException: "Could not load type "App\Form\DependentFilteredEntityType": class does not exist." at C:\Bitnami\wappstack\apache2\htdocs\topbusiness\vendor\symfony\form\FormRegistry.php line 86 {"exception":"[object] (Symfony\\Component\\Form\\Exception\\InvalidArgumentException(code: 0): Could not load type \"App\\Form\\DependentFilteredEntityType\": class does not exist. at C:\\Bitnami\\wappstack\\apache2\\htdocs\\topbusiness\\vendor\\symfony\\form\\FormRegistry.php:86)"} []

**Comment by methodeprog** [comment]
All excuse i try to define // DependentFilteredEntityType // it now

**Comment by perkelekurat** [comment]
Looks like you're doing it wrong. DependentFilteredEntityType class is located in the bundle's Form namespace, not in App\*.
